language: groovy
jdk:
- oraclejdk7
after_success:
- ./gradlew  bintrayUpload -PbtIdentity="${btIdentity}" -PbtIDCreds="${btIDCreds}"
env:
  global:
  - secure: moaThCKPFPDfGD+cAUHGwajGJz+oK8s9jKlA94c05X+ZEQ02iiOVK60FXn5AGjz+240IolEh4ve5FvmWWbQtMrPOgG5m+cXV/2v27J5HvagLtJSQf0rJbiAVknosoe8whNPEFRQl2n5ASLpyllA9AhywZpntzGRGAuKQk7BpDgs=
  - secure: BmjsGczSbhzHYg/MG8B2VkFn4eERTFUkJNUxOGrfKr9WHgZO+FxkAbFlwIWwAmnq7+PBUYlPCHVGmTJhq7eztMvPMh+r15K81YWP9KkTQyqdyLahiaPjTadP4GNzhDPiqLxEuW238f6CKZPKEdwMWPRZfizIKXIsqKKVl1XzbaU=
